image: atlassian/default-image:2

definitions:
  steps:
    - step: &build-artifact
        caches:
          - maven
        script:
          - mvn -B package
        artifacts:
          - target/jol.war

pipelines:
  branches:
    release/*:
      - step: *build-artifact
      - step:
          name: Deploy to prod
          deployment: production
          services:
            - docker
          script:
            - mkdir -p ~/.docker
            - echo $TLSCACERT | base64 --decode  > ~/.docker/ca.pem
            - echo $TLSCERT | base64 --decode  > ~/.docker/cert.pem
            - echo $TLSKEY | base64 --decode  > ~/.docker/key.pem
            - export DOCKER_TLS_VERIFY="1"
            - export DOCKER_HOST="$DOCKER_HOST"
            - export DOCKER_CERT_PATH=~/.docker
            - export DOCKER_MACHINE_NAME="jol"
            - docker cp target/jol.war prod:/usr/local/tomcat/webapps/
    develop:
      - step: *build-artifact
      - step:
          name: Deploy to test
          deployment: test
          services:
            - docker
          script:
            - mkdir -p ~/.docker
            - echo $TLSCACERT | base64 --decode  > ~/.docker/ca.pem
            - echo $TLSCERT | base64 --decode  > ~/.docker/cert.pem
            - echo $TLSKEY | base64 --decode  > ~/.docker/key.pem
            - export DOCKER_TLS_VERIFY="1"
            - export DOCKER_HOST="$DOCKER_HOST"
            - export DOCKER_CERT_PATH=~/.docker
            - export DOCKER_MACHINE_NAME="jol"
            - docker cp target/jol.war test:/usr/local/tomcat/webapps/