image: atlassian/default-image:2

definitions:
  steps:
    - step: &build-artifact
        name: Build artifact
        image: maven:3.9-amazoncorretto-11
        caches:
          - maven
        script:
          - mvn -B package
        artifacts:
          - target/jol.war

pipelines:
  branches:
    release/*:
      - step: *build-artifact
      - step:
          name: Deploy to prod
          deployment: production
          services:
            - docker
          script:
            - docker cp target/jol.war prod:/usr/local/tomcat/webapps/
    develop:
      - step: *build-artifact
      - step:
          name: Deploy to test
          deployment: test
          services:
            - docker
          script:
            - DOCKER_HOST=$DECKSERVER_HOST docker cp target/jol.war test:/usr/local/tomcat/webapps/