services:
  prod:
    image: tomcat:9-jdk13-openjdk-buster
    container_name: prod
    networks:
      - web
    labels:
      - "traefik.http.routers.prod.entrypoints=websecure"
      - "traefik.http.routers.prod.rule=Host(`www.deckserver.net`) || Host(`deckserver.net`)"
      - "traefik.http.routers.prod.tls.certresolver=myresolver"
    environment:
      JOL_DATA: /data
      JOL_VERSION: 25-Oct-2024
      JOL_RECAPTCHA_KEY: "***REMOVED***"
      JOL_RECAPTCHA_SECRET: "***REMOVED***"
      _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
      DISCORD_API_VERSION: 6
      DISCORD_BOT_TOKEN: "***REMOVED***"
      DISCORD_PING_CHANNEL_ID: 455542605535510529
    volumes:
      - prod-data:/data
      - prod-app:/usr/local/tomcat/webapps
  static:
    image: nginx
    container_name: static
    networks:
      - web
    labels:
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.rule=Host(`static.deckserver.net`)"
      - "traefik.http.routers.static.tls.certresolver=myresolver"
    volumes:
      - static-data:/usr/share/nginx/html
      - ./nginx/:/etc/nginx/conf.d/
networks:
  web:
    external: true
volumes:
  prod-data:
    external: true
  prod-app:
    external: true
  static-data:
    external: true