version: "3.7"
services:
  test:
    image: tomcat:9-jdk13-openjdk-buster
    container_name: test
    networks:
      - web
    labels:
      - "traefik.http.routers.jol.entrypoints=websecure"
      - "traefik.http.routers.jol.rule=Host(`test.deckserver.net`)"
      - "traefik.http.routers.jol.tls.certresolver=myresolver"
    environment:
      JOL_DATA: /data
      JOL_VERSION: docker-version
      JOL_RECAPTCHA_KEY: ***REMOVED***
      JOL_RECAPTCHA_SECRET: ***REMOVED***
    volumes:
      - test-data:/data
      - test-app:/usr/local/tomcat/webapps
  prod:
    image: tomcat:9-jdk13-openjdk-buster
    container_name: prod
    networks:
      - web
    labels:
      - "traefik.http.routers.prod.entrypoints=websecure"
      - "traefik.http.routers.prod.rule=Host(`www.deckserver.net`) || Host(`deckserver.net`)"
      - "traefik.http.routers.prod.tls.certresolver=myresolver"
    environment:
      JOL_DATA: /data
      JOL_VERSION: 1.2.0-prod
      JOL_RECAPTCHA_KEY: ***REMOVED***
      JOL_RECAPTCHA_SECRET: ***REMOVED***
      DISCORD_API_VERSION: 6
      DISCORD_BOT_TOKEN: ***REMOVED***
      DISCORD_PING_CHANNEL_ID: 455542605535510529
    volumes:
      - prod-data:/data
      - prod-app:/usr/local/tomcat/webapps
networks:
  web:
    external: true
volumes:
  test-data:
    external: true
  test-app:
    external: true
  prod-data:
    external: true
  prod-app:
    external: true