server {
    listen 80;
    server_name static.dev.deckserver.net;

    location / {
        root /var/static;

        location ~ /assets {
            root /var;
            include conf.d/cors.txt;
        }

        location ~ /html {
            include conf.d/cors.txt;
            default_type text/html;
        }

        location ~ /secured/html {
            include conf.d/cors.txt;
            default_type text/html;
        }

        location ~ /json {
            include conf.d/cors.txt;
            default_type application/json;
        }

        location ~ /secured/json {
            include conf.d/cors.txt;
            default_type application/json;
        }

        location ~ /images {
            include conf.d/cors.txt;
            default_type image/jpeg;
        }

        location ~ /secured/images {
            include conf.d/cors.txt;
            default_type image/jpeg;
        }
    }
}