package net.deckserver.storage.json.game;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.regex.Pattern;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Data
public class ChatData {

    private static final DateTimeFormatter SIMPLE_FORMAT = DateTimeFormatter.ofPattern("d-MMM HH:mm ");
    /** Every phase marker is generated by {@code JolGame.setPhase} as exactly this shape. */
    private static final Pattern PHASE_LINE = Pattern.compile("(?i)^start of .+ phase\\.?\\s*$");

    private String timestamp;
    private String message;
    private String source;
    private String command;
    /**
     * Coarse line category the chat log filters on ({@code talk} / {@code move}
     * / {@code phase} / {@code system}). Derived from {@link #source} +
     * {@link #command} + {@link #message} — see {@link #getKind()} — so it needs
     * no column and works for historical rows. Held as a field only so
     * {@link #forSeatedView()} can freeze it before {@link #command} is dropped.
     * Leak-free (a bare category, no card id), so it survives to every viewer.
     */
    private String kind;
    /** Raw text the player submitted for the command that produced this line. Judge-only; stripped for other viewers. */
    private String invocation;
    /** Who issued that command — often not {@link #source}, which is frequently the affected player. Judge-only. */
    private String invocationBy;
    /**
     * Monotonic id identifying the single command submission that produced this line —
     * shared by every line that submission emitted, distinct for the next one even
     * when {@link #invocation} is byte-identical. Lets judges' chat log show the
     * "» command" header once per submission rather than once per distinct text.
     * Judge-only; stripped for other viewers.
     */
    private Long invocationSeq;
    /**
     * Full-precision ISO-8601 insert time ({@code game_chat_message.posted_at}), as
     * opposed to the minute-granularity display string in {@link #timestamp}. Lets
     * the judges' chat log interleave failed command attempts
     * ({@link CommandErrorData#getOccurredAt()}) at their true chronological position
     * rather than rounding to the minute.
     */
    private String postedAt;

    public ChatData() {
    }

    public ChatData(String message, String source, String command) {
        this.timestamp = OffsetDateTime.now().format(SIMPLE_FORMAT);
        this.message = message;
        this.source = source;
        this.command = command;
    }

    public ChatData(OffsetDateTime timestamp, String message, String source) {
        this.timestamp = timestamp.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        this.message = message;
        this.source = source;
    }

    /**
     * A copy carrying only the fields a seated player / spectator may see:
     * {@link #command}, {@link #invocation}, {@link #invocationBy} and
     * {@link #invocationSeq} are judge-only (a judge watching a game they are
     * not seated in) — the structured command carries the real card id even
     * for a face-down play/move, so it must never reach a seated opponent's
     * client. The client does not render them for anyone else anyway.
     */
    public ChatData forSeatedView() {
        ChatData copy = new ChatData();
        copy.timestamp = this.timestamp;
        copy.postedAt = this.postedAt;
        copy.message = this.message;
        copy.source = this.source;
        copy.kind = this.getKind(); // freeze — the copy has no `command` to derive it from
        return copy;
    }

    /**
     * {@code talk} — a player (or judge) said something to the table;
     * {@code move} — the log line a command produced;
     * {@code phase} — a "Start of X phase." marker;
     * {@code system} — any other machine line (turn, oust, timeout, contest…).
     * The chat log's All / Talk toggle shows only {@code talk} + {@code system}.
     */
    public String getKind() {
        if (kind != null) {
            return kind;
        }
        // Checked before the source test so legacy rows (pre-U1, when phase
        // markers were attributed to the active player, not SYSTEM) still
        // classify as "phase" and stay out of the Talk view.
        if (message != null && PHASE_LINE.matcher(message).matches()) {
            return "phase";
        }
        if ("SYSTEM".equals(source)) {
            return "system";
        }
        return command != null && !command.isBlank() ? "move" : "talk";
    }
}